version: "3.4"
services:

  backend:
    container_name: backend
    hostname: backend
    build:
      dockerfile: backend/Dockerfile
      target: "backend"
    ports:
      - "8080:8080"
    networks:
      - priv-network
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_KEY:
      CROSS_ORIGIN: http://localhost:4200

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:80"
    volumes: # Volume binding
      - './frontend/tick-tack-toe:/usr/src/app'
    networks:
      - priv-network
    environment:
      BASE_URL: localhost

networks:
  priv-network:
    driver: bridge